spring.application.name=SOCApplication

spring.datasource.url = jdbc:h2:mem:practice
spring.datasource.username = sahil
spring.datasource.password = sahil123
spring.datasource.driverClassName = org.h2.Driver

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true

aws.access-key = ${AWS_ACCESS_KEY}
aws.secret-key = ${AWS_SECRET_KEY}
aws.region = ap-southeast-2
aws.bucket-name=my-rag-bucker-123

spring.servlet.multipart.max-file-size = 50MB
spring.servlet.multipart.max-request-size= 50MB